-- DUMP SCHEMA
-- Run this in the Supabase SQL editor to get the live database's schema (the
-- public tables, indexes, functions, triggers and row-level-security rules,
-- plus the storage-bucket rules) back as ONE cell of SQL that rebuilds it.
-- Paste that cell into db/schema.sql to refresh the snapshot after changes.
-- Read-only: it only reads the catalogs, nothing is changed.
with
tabs as (
  select c.oid, c.relname from pg_class c
  where c.relnamespace = 'public'::regnamespace and c.relkind = 'r'
),
cols as (
  select t.relname, a.attnum,
    format('  %I %s%s%s', a.attname, format_type(a.atttypid, a.atttypmod),
      case when a.attidentity = 'd' then ' generated by default as identity'
           when a.attidentity = 'a' then ' generated always as identity'
           when a.attgenerated = 's' then ' generated always as (' || pg_get_expr(d.adbin, d.adrelid) || ') stored'
           when d.adbin is not null then ' default ' || pg_get_expr(d.adbin, d.adrelid) else '' end,
      case when a.attnotnull then ' not null' else '' end) as line
  from tabs t join pg_attribute a on a.attrelid = t.oid and a.attnum > 0 and not a.attisdropped
  left join pg_attrdef d on d.adrelid = t.oid and d.adnum = a.attnum
),
stmts as (
  select 10 as grp, relname as k, 0 as sub,
    format(E'create table public.%I (\n%s\n);', relname, string_agg(line, E',\n' order by attnum)) as ddl
  from cols group by relname
  union all
  select case when con.contype = 'f' then 30 else 20 end, cl.relname || '.' || con.conname, 0,
    format('alter table public.%I add constraint %I %s;', cl.relname, con.conname, pg_get_constraintdef(con.oid))
  from pg_constraint con join pg_class cl on cl.oid = con.conrelid
  where cl.relnamespace = 'public'::regnamespace and con.contype in ('p','u','c','f','x')
  union all
  select 40, i.indexname, 0, i.indexdef || ';'
  from pg_indexes i
  where i.schemaname = 'public'
    and not exists (select 1 from pg_constraint con where con.conindid = (quote_ident(i.schemaname) || '.' || quote_ident(i.indexname))::regclass)
  union all
  select 50, p.proname || '(' || pg_get_function_identity_arguments(p.oid) || ')', 0, pg_get_functiondef(p.oid) || ';'
  from pg_proc p
  where p.pronamespace = 'public'::regnamespace and p.prokind in ('f','p')
    and not exists (select 1 from pg_depend dep where dep.objid = p.oid and dep.deptype = 'e')
  union all
  select 60, c.relname, 0, format(E'create view public.%I as\n%s', c.relname, pg_get_viewdef(c.oid, true))
  from pg_class c where c.relnamespace = 'public'::regnamespace and c.relkind = 'v'
  union all
  select 70, tg.tgname, 0, pg_get_triggerdef(tg.oid) || ';'
  from pg_trigger tg join pg_class c on c.oid = tg.tgrelid
  join pg_proc p on p.oid = tg.tgfoid
  where not tg.tgisinternal
    and (c.relnamespace = 'public'::regnamespace or p.pronamespace = 'public'::regnamespace)
  union all
  select 80, c.relname, 0, format('alter table %s enable row level security;', c.oid::regclass)
  from pg_class c
  where c.relrowsecurity and c.relkind = 'r'
    and (c.relnamespace = 'public'::regnamespace)
  union all
  select 90, c.oid::regclass::text || '.' || pol.polname, 0,
    format('create policy %I on %s as %s for %s to %s%s%s;',
      pol.polname, c.oid::regclass,
      case when pol.polpermissive then 'permissive' else 'restrictive' end,
      case pol.polcmd when 'r' then 'select' when 'a' then 'insert' when 'w' then 'update' when 'd' then 'delete' else 'all' end,
      case when pol.polroles = '{0}' then 'public'
           else (select string_agg(quote_ident(r.rolname), ', ' order by r.rolname) from pg_roles r where r.oid = any(pol.polroles)) end,
      case when pol.polqual is not null then E'\n  using (' || pg_get_expr(pol.polqual, pol.polrelid) || ')' else '' end,
      case when pol.polwithcheck is not null then E'\n  with check (' || pg_get_expr(pol.polwithcheck, pol.polrelid) || ')' else '' end)
  from pg_policy pol join pg_class c on c.oid = pol.polrelid
  where c.relnamespace in ('public'::regnamespace, 'storage'::regnamespace)
)
select 'set check_function_bodies = off;' || E'\n\n' || string_agg(ddl, E'\n\n' order by grp, k, sub) || E'\n' as schema_sql
from stmts;
