-- ==========================================================================
-- SNAPSHOT of the live Tobe-Fit database, taken 2026-10-09 from Supabase:
-- the public tables, indexes, functions, triggers, row-level-security rules
-- and the storage-bucket rules. This is the source of truth for "what the
-- database looks like right now".
--
-- For reading and for building a throwaway copy (tests, a second project).
-- NOT meant to be run on the live database - it creates things without
-- "if not exists". It needs Supabase's own auth and storage schemas.
--
-- Changes since this snapshot live in db/changes/ (see db/README.md).
-- Refresh the snapshot with db/dump-schema.sql.
-- ==========================================================================

set check_function_bodies = off;

create table public.athlete_label_links (
  athlete_id bigint not null,
  label_id uuid not null
);

create table public.athlete_labels (
  id uuid default gen_random_uuid() not null,
  coach_id uuid not null,
  name text not null,
  created_at timestamp with time zone default now() not null
);

create table public.athlete_metrics (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone default now() not null,
  athlete_id bigint,
  metric_id bigint
);

create table public.athlete_notes (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone default now() not null,
  athlete_id bigint,
  date date,
  note text
);

create table public.athlete_stretch_preferences (
  id uuid default gen_random_uuid() not null,
  athlete_id bigint not null,
  stretch_id uuid not null,
  preference text not null,
  created_at timestamp with time zone default now() not null
);

create table public.athletes (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone default now() not null,
  name text,
  date_of_birth date,
  gender text,
  height smallint,
  weight smallint,
  notes text,
  coach_id uuid,
  user_id uuid,
  email text,
  can_preview_next_week boolean default false not null,
  weight_unit text default 'kg'::text not null,
  weekly_recap_enabled boolean default true not null,
  can_self_log_workouts boolean default true not null,
  archived boolean default false not null,
  can_add_exercises boolean default false not null,
  can_change_exercises boolean default false not null,
  can_reschedule_workouts boolean default false not null,
  can_view_weekly_stats boolean default true not null,
  avatar_url text,
  intro_seen boolean default false not null,
  mobility_enabled boolean default true not null,
  tournaments_enabled boolean default true not null,
  low_trainings_notified_for text
);

create table public.bodyweight (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone default now() not null,
  athlete_id bigint,
  date date,
  weight real,
  notes text
);

create table public.chat_messages (
  id uuid default gen_random_uuid() not null,
  coach_id uuid not null,
  athlete_id bigint not null,
  sender text not null,
  message text default ''::text not null,
  pdf_url text,
  created_at timestamp with time zone default now() not null,
  read_at timestamp with time zone
);

create table public.coach_messages (
  id uuid default gen_random_uuid() not null,
  coach_id uuid not null,
  athlete_id bigint not null,
  message text not null,
  timing text not null,
  seen_at timestamp with time zone,
  created_at timestamp with time zone default now() not null
);

create table public.exercise_log_sets (
  id uuid default gen_random_uuid() not null,
  program_exercise_id uuid not null,
  athlete_id bigint not null,
  date date default CURRENT_DATE not null,
  set_number integer not null,
  actual_reps text,
  actual_weight numeric,
  completed_at timestamp with time zone,
  created_at timestamp with time zone default now() not null,
  actual_distance numeric,
  weight_unit text,
  actual_duration text
);

create table public.exercises (
  id uuid default gen_random_uuid() not null,
  coach_id uuid not null,
  name text not null,
  category text,
  instructions text,
  created_at timestamp with time zone default now() not null,
  type text default 'weights'::text not null,
  video_url text,
  foot_contacts integer,
  intensity_tier text,
  tracks_weight boolean default true not null,
  is_timed boolean default false not null,
  is_unilateral boolean default false not null,
  tracks_distance boolean default false not null,
  tracks_reps boolean default true not null,
  archived boolean default false not null
);

create table public.extra_field_names (
  id uuid default gen_random_uuid() not null,
  coach_id uuid not null,
  name text not null,
  created_at timestamp with time zone default now() not null
);

create table public.form_answers (
  id uuid default gen_random_uuid() not null,
  assignment_id uuid not null,
  question_id uuid not null,
  answer_text text,
  answer_scale integer,
  created_at timestamp with time zone default now() not null
);

create table public.form_assignments (
  id uuid default gen_random_uuid() not null,
  coach_id uuid not null,
  athlete_id bigint not null,
  form_id uuid not null,
  date date not null,
  completed_at timestamp with time zone,
  created_at timestamp with time zone default now() not null
);

create table public.form_questions (
  id uuid default gen_random_uuid() not null,
  form_id uuid not null,
  order_index integer default 0 not null,
  question_text text not null,
  type text not null,
  created_at timestamp with time zone default now() not null
);

create table public.forms (
  id uuid default gen_random_uuid() not null,
  coach_id uuid not null,
  name text not null,
  gate_workout boolean default false not null,
  created_at timestamp with time zone default now() not null
);

create table public.measurements (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone default now() not null,
  athlete_id bigint,
  metric_id bigint,
  value real,
  date date,
  notes text,
  height real,
  ground_contact real,
  rsi real,
  pace real,
  bpm smallint,
  distance real,
  duration real
);

create table public.metrics (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone default now() not null,
  name text,
  unit text,
  type text,
  display_unit text,
  higher_is_better boolean,
  category text
);

create table public.notifications (
  id uuid default gen_random_uuid() not null,
  coach_id uuid not null,
  athlete_id bigint,
  type text not null,
  message text not null,
  read_at timestamp with time zone,
  created_at timestamp with time zone default now() not null
);

create table public.profiles (
  id uuid not null,
  role text not null,
  name text,
  created_at timestamp with time zone default now() not null,
  mobility_enabled boolean default true not null,
  low_trainings_warning_days integer default 7 not null
);

create table public.program_days (
  id uuid default gen_random_uuid() not null,
  week_id uuid not null,
  day_number integer not null,
  label text,
  date_override date,
  workout_type text,
  source_training_id uuid,
  source_training_synced_at timestamp with time zone,
  moved_by_athlete boolean default false not null
);

create table public.program_exercises (
  id uuid default gen_random_uuid() not null,
  day_id uuid not null,
  exercise_id uuid not null,
  order_index integer default 0 not null,
  prescribed_sets integer,
  prescribed_reps text,
  prescribed_weight numeric,
  notes text,
  created_at timestamp with time zone default now() not null,
  extra_fields jsonb,
  rest_seconds integer,
  set_targets jsonb,
  section_label text,
  superset_group_id uuid,
  added_by_athlete boolean default false not null,
  swapped_by_athlete boolean default false not null,
  original_exercise_id uuid,
  section_instance_id uuid,
  tracks_weight_override boolean,
  is_timed_override boolean,
  is_unilateral_override boolean,
  tracks_distance_override boolean,
  alternative_exercise_id uuid
);

create table public.program_weeks (
  id uuid default gen_random_uuid() not null,
  program_id uuid not null,
  week_number integer not null
);

create table public.programs (
  id uuid default gen_random_uuid() not null,
  coach_id uuid not null,
  athlete_id bigint,
  name text not null,
  start_date date,
  created_at timestamp with time zone default now() not null,
  is_template boolean default false not null,
  is_adhoc boolean default false not null,
  created_by_athlete boolean default false not null
);

create table public.push_subscriptions (
  id uuid default gen_random_uuid() not null,
  user_id uuid not null,
  endpoint text not null,
  p256dh text not null,
  auth_key text not null,
  created_at timestamp with time zone default now() not null
);

create table public.scheduled_notifications (
  id uuid default gen_random_uuid() not null,
  user_id uuid not null,
  fire_at timestamp with time zone not null,
  title text not null,
  body text not null,
  url text,
  created_at timestamp with time zone default now() not null
);

create table public.section_exercises (
  id uuid default gen_random_uuid() not null,
  section_id uuid not null,
  exercise_id uuid not null,
  order_index integer default 0 not null,
  prescribed_sets integer,
  prescribed_reps text,
  prescribed_weight numeric,
  rest_seconds integer,
  extra_fields jsonb,
  notes text,
  set_targets jsonb,
  created_at timestamp with time zone default now() not null,
  superset_group_id uuid,
  tracks_weight_override boolean,
  is_timed_override boolean,
  is_unilateral_override boolean,
  tracks_distance_override boolean,
  alternative_exercise_id uuid
);

create table public.sections (
  id uuid default gen_random_uuid() not null,
  coach_id uuid not null,
  name text not null,
  created_at timestamp with time zone default now() not null
);

create table public.stretch_body_areas (
  id uuid default gen_random_uuid() not null,
  coach_id uuid not null,
  name text not null,
  created_at timestamp with time zone default now() not null
);

create table public.stretches (
  id uuid default gen_random_uuid() not null,
  coach_id uuid not null,
  name text not null,
  body_areas text[] default '{}'::text[] not null,
  video_url text,
  default_hold_seconds integer default 30 not null,
  created_at timestamp with time zone default now() not null,
  is_unilateral boolean default false not null
);

create table public.tournament_coach_ratings (
  tournament_id uuid not null,
  importance integer not null,
  created_at timestamp with time zone default now() not null
);

create table public.tournaments (
  id uuid default gen_random_uuid() not null,
  athlete_id bigint not null,
  name text not null,
  date date not null,
  importance integer,
  created_at timestamp with time zone default now() not null,
  end_date date not null,
  created_by_coach boolean default false not null
);

create table public.training_exercises (
  id uuid default gen_random_uuid() not null,
  training_id uuid not null,
  exercise_id uuid not null,
  order_index integer default 0 not null,
  prescribed_sets integer,
  prescribed_reps text,
  prescribed_weight numeric,
  extra_fields jsonb,
  notes text,
  created_at timestamp with time zone default now() not null,
  rest_seconds integer,
  set_targets jsonb,
  section_label text,
  superset_group_id uuid,
  section_instance_id uuid,
  tracks_weight_override boolean,
  is_timed_override boolean,
  is_unilateral_override boolean,
  tracks_distance_override boolean,
  alternative_exercise_id uuid
);

create table public.training_label_links (
  training_id uuid not null,
  label_id uuid not null
);

create table public.training_labels (
  id uuid default gen_random_uuid() not null,
  coach_id uuid not null,
  name text not null,
  created_at timestamp with time zone default now() not null
);

create table public.trainings (
  id uuid default gen_random_uuid() not null,
  coach_id uuid not null,
  name text not null,
  created_at timestamp with time zone default now() not null,
  workout_type text default 'gym'::text not null,
  updated_at timestamp with time zone default now() not null
);

create table public.workout_sessions (
  id uuid default gen_random_uuid() not null,
  program_day_id uuid,
  athlete_id bigint not null,
  started_at timestamp with time zone default now() not null,
  ended_at timestamp with time zone,
  created_at timestamp with time zone default now() not null,
  session_rpe integer,
  session_type text default 'training'::text not null,
  avg_heart_rate integer,
  rpe_flag_reason text,
  rpe_flag_note text,
  rpe_flag_reviewed_at timestamp with time zone,
  local_date date not null,
  mobility_focus_areas text[],
  athlete_note text
);

alter table public.athlete_label_links add constraint athlete_label_links_pkey PRIMARY KEY (athlete_id, label_id);

alter table public.athlete_labels add constraint athlete_labels_pkey PRIMARY KEY (id);

alter table public.athlete_metrics add constraint athlete_metrics_pkey PRIMARY KEY (id);

alter table public.athlete_notes add constraint athlete_notes_pkey PRIMARY KEY (id);

alter table public.athlete_stretch_preferences add constraint athlete_stretch_preferences_athlete_id_stretch_id_key UNIQUE (athlete_id, stretch_id);

alter table public.athlete_stretch_preferences add constraint athlete_stretch_preferences_pkey PRIMARY KEY (id);

alter table public.athlete_stretch_preferences add constraint athlete_stretch_preferences_preference_check CHECK ((preference = ANY (ARRAY['liked'::text, 'disliked'::text])));

alter table public.athletes add constraint "Athletes_pkey" PRIMARY KEY (id);

alter table public.athletes add constraint athletes_weight_unit_check CHECK ((weight_unit = ANY (ARRAY['kg'::text, 'lbs'::text])));

alter table public.bodyweight add constraint bodyweight_pkey PRIMARY KEY (id);

alter table public.chat_messages add constraint chat_messages_check CHECK (((message <> ''::text) OR (pdf_url IS NOT NULL)));

alter table public.chat_messages add constraint chat_messages_pkey PRIMARY KEY (id);

alter table public.chat_messages add constraint chat_messages_sender_check CHECK ((sender = ANY (ARRAY['coach'::text, 'athlete'::text])));

alter table public.coach_messages add constraint coach_messages_pkey PRIMARY KEY (id);

alter table public.coach_messages add constraint coach_messages_timing_check CHECK ((timing = ANY (ARRAY['on_open'::text, 'before_workout'::text, 'push'::text])));

alter table public.exercise_log_sets add constraint exercise_log_sets_pkey PRIMARY KEY (id);

alter table public.exercise_log_sets add constraint exercise_log_sets_program_exercise_id_date_set_number_key UNIQUE (program_exercise_id, date, set_number);

alter table public.exercise_log_sets add constraint exercise_log_sets_weight_unit_check CHECK ((weight_unit = ANY (ARRAY['kg'::text, 'lbs'::text])));

alter table public.exercises add constraint exercises_intensity_tier_check CHECK ((intensity_tier = ANY (ARRAY['low'::text, 'moderate'::text, 'high'::text])));

alter table public.exercises add constraint exercises_pkey PRIMARY KEY (id);

alter table public.extra_field_names add constraint extra_field_names_coach_id_name_key UNIQUE (coach_id, name);

alter table public.extra_field_names add constraint extra_field_names_pkey PRIMARY KEY (id);

alter table public.form_answers add constraint form_answers_answer_scale_check CHECK (((answer_scale >= 1) AND (answer_scale <= 5)));

alter table public.form_answers add constraint form_answers_assignment_id_question_id_key UNIQUE (assignment_id, question_id);

alter table public.form_answers add constraint form_answers_pkey PRIMARY KEY (id);

alter table public.form_assignments add constraint form_assignments_pkey PRIMARY KEY (id);

alter table public.form_questions add constraint form_questions_pkey PRIMARY KEY (id);

alter table public.form_questions add constraint form_questions_type_check CHECK ((type = ANY (ARRAY['short_text'::text, 'long_text'::text, 'scale_1_5'::text])));

alter table public.forms add constraint forms_pkey PRIMARY KEY (id);

alter table public.measurements add constraint measurements_pkey PRIMARY KEY (id);

alter table public.metrics add constraint metrics_pkey PRIMARY KEY (id);

alter table public.notifications add constraint notifications_pkey PRIMARY KEY (id);

alter table public.notifications add constraint notifications_type_check CHECK ((type = ANY (ARRAY['workout_added'::text, 'workout_completed'::text, 'tournament_added'::text, 'low_trainings'::text, 'chat_message'::text, 'workout_note'::text])));

alter table public.profiles add constraint profiles_pkey PRIMARY KEY (id);

alter table public.profiles add constraint profiles_role_check CHECK ((role = ANY (ARRAY['coach'::text, 'athlete'::text])));

alter table public.program_days add constraint program_days_pkey PRIMARY KEY (id);

alter table public.program_days add constraint program_days_week_id_day_number_key UNIQUE (week_id, day_number);

alter table public.program_days add constraint program_days_workout_type_check CHECK ((workout_type = ANY (ARRAY['gym'::text, 'field'::text, 'run'::text])));

alter table public.program_exercises add constraint program_exercises_pkey PRIMARY KEY (id);

alter table public.program_weeks add constraint program_weeks_pkey PRIMARY KEY (id);

alter table public.program_weeks add constraint program_weeks_program_id_week_number_key UNIQUE (program_id, week_number);

alter table public.programs add constraint programs_pkey PRIMARY KEY (id);

alter table public.push_subscriptions add constraint push_subscriptions_endpoint_key UNIQUE (endpoint);

alter table public.push_subscriptions add constraint push_subscriptions_pkey PRIMARY KEY (id);

alter table public.scheduled_notifications add constraint scheduled_notifications_pkey PRIMARY KEY (id);

alter table public.section_exercises add constraint section_exercises_pkey PRIMARY KEY (id);

alter table public.sections add constraint sections_pkey PRIMARY KEY (id);

alter table public.stretch_body_areas add constraint stretch_body_areas_coach_id_name_key UNIQUE (coach_id, name);

alter table public.stretch_body_areas add constraint stretch_body_areas_pkey PRIMARY KEY (id);

alter table public.stretches add constraint stretches_pkey PRIMARY KEY (id);

alter table public.tournament_coach_ratings add constraint tournament_coach_ratings_importance_check CHECK (((importance >= 1) AND (importance <= 5)));

alter table public.tournament_coach_ratings add constraint tournament_coach_ratings_pkey PRIMARY KEY (tournament_id);

alter table public.tournaments add constraint tournaments_end_after_start CHECK ((end_date >= date));

alter table public.tournaments add constraint tournaments_importance_check CHECK (((importance >= 1) AND (importance <= 5)));

alter table public.tournaments add constraint tournaments_pkey PRIMARY KEY (id);

alter table public.tournaments add constraint tournaments_rating_owner CHECK (((created_by_coach AND (importance IS NULL)) OR ((NOT created_by_coach) AND (importance IS NOT NULL))));

alter table public.training_exercises add constraint training_exercises_pkey PRIMARY KEY (id);

alter table public.training_label_links add constraint training_label_links_pkey PRIMARY KEY (training_id, label_id);

alter table public.training_labels add constraint training_labels_pkey PRIMARY KEY (id);

alter table public.trainings add constraint trainings_pkey PRIMARY KEY (id);

alter table public.trainings add constraint trainings_workout_type_check CHECK ((workout_type = ANY (ARRAY['gym'::text, 'field'::text, 'run'::text])));

alter table public.workout_sessions add constraint workout_sessions_avg_heart_rate_check CHECK (((avg_heart_rate IS NULL) OR ((avg_heart_rate >= 30) AND (avg_heart_rate <= 250))));

alter table public.workout_sessions add constraint workout_sessions_pkey PRIMARY KEY (id);

alter table public.workout_sessions add constraint workout_sessions_rpe_flag_reason_check CHECK ((rpe_flag_reason = ANY (ARRAY['pain_injury'::text, 'heavy_tiring'::text])));

alter table public.workout_sessions add constraint workout_sessions_session_rpe_check CHECK (((session_rpe >= 1) AND (session_rpe <= 10)));

alter table public.workout_sessions add constraint workout_sessions_session_type_check CHECK ((session_type = ANY (ARRAY['training'::text, 'mobility'::text])));

alter table public.workout_sessions add constraint workout_sessions_training_needs_day CHECK (((session_type <> 'training'::text) OR (program_day_id IS NOT NULL)));

alter table public.athlete_label_links add constraint athlete_label_links_athlete_id_fkey FOREIGN KEY (athlete_id) REFERENCES athletes(id) ON DELETE CASCADE;

alter table public.athlete_label_links add constraint athlete_label_links_label_id_fkey FOREIGN KEY (label_id) REFERENCES athlete_labels(id) ON DELETE CASCADE;

alter table public.athlete_labels add constraint athlete_labels_coach_id_fkey FOREIGN KEY (coach_id) REFERENCES auth.users(id);

alter table public.athlete_stretch_preferences add constraint athlete_stretch_preferences_athlete_id_fkey FOREIGN KEY (athlete_id) REFERENCES athletes(id) ON DELETE CASCADE;

alter table public.athlete_stretch_preferences add constraint athlete_stretch_preferences_stretch_id_fkey FOREIGN KEY (stretch_id) REFERENCES stretches(id) ON DELETE CASCADE;

alter table public.athletes add constraint athletes_coach_id_fkey FOREIGN KEY (coach_id) REFERENCES auth.users(id);

alter table public.athletes add constraint athletes_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id);

alter table public.chat_messages add constraint chat_messages_athlete_id_fkey FOREIGN KEY (athlete_id) REFERENCES athletes(id) ON DELETE CASCADE;

alter table public.chat_messages add constraint chat_messages_coach_id_fkey FOREIGN KEY (coach_id) REFERENCES auth.users(id);

alter table public.coach_messages add constraint coach_messages_athlete_id_fkey FOREIGN KEY (athlete_id) REFERENCES athletes(id) ON DELETE CASCADE;

alter table public.coach_messages add constraint coach_messages_coach_id_fkey FOREIGN KEY (coach_id) REFERENCES auth.users(id);

alter table public.exercise_log_sets add constraint exercise_log_sets_athlete_id_fkey FOREIGN KEY (athlete_id) REFERENCES athletes(id) ON DELETE CASCADE;

alter table public.exercise_log_sets add constraint exercise_log_sets_program_exercise_id_fkey FOREIGN KEY (program_exercise_id) REFERENCES program_exercises(id) ON DELETE CASCADE;

alter table public.exercises add constraint exercises_coach_id_fkey FOREIGN KEY (coach_id) REFERENCES auth.users(id);

alter table public.extra_field_names add constraint extra_field_names_coach_id_fkey FOREIGN KEY (coach_id) REFERENCES auth.users(id);

alter table public.form_answers add constraint form_answers_assignment_id_fkey FOREIGN KEY (assignment_id) REFERENCES form_assignments(id) ON DELETE CASCADE;

alter table public.form_answers add constraint form_answers_question_id_fkey FOREIGN KEY (question_id) REFERENCES form_questions(id) ON DELETE CASCADE;

alter table public.form_assignments add constraint form_assignments_athlete_id_fkey FOREIGN KEY (athlete_id) REFERENCES athletes(id) ON DELETE CASCADE;

alter table public.form_assignments add constraint form_assignments_coach_id_fkey FOREIGN KEY (coach_id) REFERENCES auth.users(id);

alter table public.form_assignments add constraint form_assignments_form_id_fkey FOREIGN KEY (form_id) REFERENCES forms(id) ON DELETE CASCADE;

alter table public.form_questions add constraint form_questions_form_id_fkey FOREIGN KEY (form_id) REFERENCES forms(id) ON DELETE CASCADE;

alter table public.forms add constraint forms_coach_id_fkey FOREIGN KEY (coach_id) REFERENCES auth.users(id);

alter table public.notifications add constraint notifications_athlete_id_fkey FOREIGN KEY (athlete_id) REFERENCES athletes(id) ON DELETE SET NULL;

alter table public.notifications add constraint notifications_coach_id_fkey FOREIGN KEY (coach_id) REFERENCES auth.users(id);

alter table public.profiles add constraint profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;

alter table public.program_days add constraint program_days_source_training_id_fkey FOREIGN KEY (source_training_id) REFERENCES trainings(id);

alter table public.program_days add constraint program_days_week_id_fkey FOREIGN KEY (week_id) REFERENCES program_weeks(id) ON DELETE CASCADE;

alter table public.program_exercises add constraint program_exercises_alternative_exercise_id_fkey FOREIGN KEY (alternative_exercise_id) REFERENCES exercises(id);

alter table public.program_exercises add constraint program_exercises_day_id_fkey FOREIGN KEY (day_id) REFERENCES program_days(id) ON DELETE CASCADE;

alter table public.program_exercises add constraint program_exercises_exercise_id_fkey FOREIGN KEY (exercise_id) REFERENCES exercises(id);

alter table public.program_exercises add constraint program_exercises_original_exercise_id_fkey FOREIGN KEY (original_exercise_id) REFERENCES exercises(id);

alter table public.program_weeks add constraint program_weeks_program_id_fkey FOREIGN KEY (program_id) REFERENCES programs(id) ON DELETE CASCADE;

alter table public.programs add constraint programs_athlete_id_fkey FOREIGN KEY (athlete_id) REFERENCES athletes(id) ON DELETE CASCADE;

alter table public.programs add constraint programs_coach_id_fkey FOREIGN KEY (coach_id) REFERENCES auth.users(id);

alter table public.push_subscriptions add constraint push_subscriptions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

alter table public.scheduled_notifications add constraint scheduled_notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

alter table public.section_exercises add constraint section_exercises_alternative_exercise_id_fkey FOREIGN KEY (alternative_exercise_id) REFERENCES exercises(id);

alter table public.section_exercises add constraint section_exercises_exercise_id_fkey FOREIGN KEY (exercise_id) REFERENCES exercises(id);

alter table public.section_exercises add constraint section_exercises_section_id_fkey FOREIGN KEY (section_id) REFERENCES sections(id) ON DELETE CASCADE;

alter table public.sections add constraint sections_coach_id_fkey FOREIGN KEY (coach_id) REFERENCES auth.users(id);

alter table public.stretch_body_areas add constraint stretch_body_areas_coach_id_fkey FOREIGN KEY (coach_id) REFERENCES auth.users(id) ON DELETE CASCADE;

alter table public.stretches add constraint stretches_coach_id_fkey FOREIGN KEY (coach_id) REFERENCES auth.users(id);

alter table public.tournament_coach_ratings add constraint tournament_coach_ratings_tournament_id_fkey FOREIGN KEY (tournament_id) REFERENCES tournaments(id) ON DELETE CASCADE;

alter table public.tournaments add constraint tournaments_athlete_id_fkey FOREIGN KEY (athlete_id) REFERENCES athletes(id) ON DELETE CASCADE;

alter table public.training_exercises add constraint training_exercises_alternative_exercise_id_fkey FOREIGN KEY (alternative_exercise_id) REFERENCES exercises(id);

alter table public.training_exercises add constraint training_exercises_exercise_id_fkey FOREIGN KEY (exercise_id) REFERENCES exercises(id);

alter table public.training_exercises add constraint training_exercises_training_id_fkey FOREIGN KEY (training_id) REFERENCES trainings(id) ON DELETE CASCADE;

alter table public.training_label_links add constraint training_label_links_label_id_fkey FOREIGN KEY (label_id) REFERENCES training_labels(id) ON DELETE CASCADE;

alter table public.training_label_links add constraint training_label_links_training_id_fkey FOREIGN KEY (training_id) REFERENCES trainings(id) ON DELETE CASCADE;

alter table public.training_labels add constraint training_labels_coach_id_fkey FOREIGN KEY (coach_id) REFERENCES auth.users(id);

alter table public.trainings add constraint trainings_coach_id_fkey FOREIGN KEY (coach_id) REFERENCES auth.users(id);

alter table public.workout_sessions add constraint workout_sessions_athlete_id_fkey FOREIGN KEY (athlete_id) REFERENCES athletes(id) ON DELETE CASCADE;

alter table public.workout_sessions add constraint workout_sessions_program_day_id_fkey FOREIGN KEY (program_day_id) REFERENCES program_days(id) ON DELETE CASCADE;

CREATE UNIQUE INDEX athletes_email_lower_key ON public.athletes USING btree (lower(email)) WHERE (email IS NOT NULL);

CREATE UNIQUE INDEX athletes_user_id_key ON public.athletes USING btree (user_id) WHERE (user_id IS NOT NULL);

CREATE INDEX idx_athlete_label_links_label_id ON public.athlete_label_links USING btree (label_id);

CREATE INDEX idx_athlete_labels_coach_id ON public.athlete_labels USING btree (coach_id);

CREATE INDEX idx_athlete_metrics_athlete_id ON public.athlete_metrics USING btree (athlete_id);

CREATE INDEX idx_athlete_notes_athlete_id ON public.athlete_notes USING btree (athlete_id);

CREATE INDEX idx_athlete_stretch_prefs_athlete_id ON public.athlete_stretch_preferences USING btree (athlete_id);

CREATE INDEX idx_athletes_coach_id ON public.athletes USING btree (coach_id);

CREATE INDEX idx_bodyweight_athlete_id ON public.bodyweight USING btree (athlete_id);

CREATE INDEX idx_chat_messages_athlete ON public.chat_messages USING btree (athlete_id, created_at);

CREATE INDEX idx_chat_messages_coach_id ON public.chat_messages USING btree (coach_id);

CREATE INDEX idx_coach_messages_coach_id ON public.coach_messages USING btree (coach_id, created_at DESC);

CREATE INDEX idx_coach_messages_unseen ON public.coach_messages USING btree (athlete_id) WHERE (seen_at IS NULL);

CREATE INDEX idx_exercise_log_sets_athlete_id ON public.exercise_log_sets USING btree (athlete_id);

CREATE INDEX idx_exercises_coach_id ON public.exercises USING btree (coach_id);

CREATE INDEX idx_extra_field_names_coach_id ON public.extra_field_names USING btree (coach_id);

CREATE INDEX idx_form_answers_question_id ON public.form_answers USING btree (question_id);

CREATE INDEX idx_form_assignments_athlete_date ON public.form_assignments USING btree (athlete_id, date);

CREATE INDEX idx_form_assignments_form_id ON public.form_assignments USING btree (form_id);

CREATE INDEX idx_form_questions_form_id ON public.form_questions USING btree (form_id);

CREATE INDEX idx_forms_coach_id ON public.forms USING btree (coach_id);

CREATE INDEX idx_measurements_athlete_id ON public.measurements USING btree (athlete_id);

CREATE INDEX idx_notifications_coach_id ON public.notifications USING btree (coach_id, created_at DESC);

CREATE INDEX idx_notifications_unread ON public.notifications USING btree (coach_id) WHERE (read_at IS NULL);

CREATE INDEX idx_program_days_source_training_id ON public.program_days USING btree (source_training_id) WHERE (source_training_id IS NOT NULL);

CREATE INDEX idx_program_days_week_id ON public.program_days USING btree (week_id);

CREATE INDEX idx_program_exercises_day_id ON public.program_exercises USING btree (day_id);

CREATE INDEX idx_program_exercises_exercise_id ON public.program_exercises USING btree (exercise_id);

CREATE INDEX idx_program_weeks_program_id ON public.program_weeks USING btree (program_id);

CREATE INDEX idx_programs_athlete_id ON public.programs USING btree (athlete_id);

CREATE INDEX idx_programs_coach_id ON public.programs USING btree (coach_id);

CREATE INDEX idx_push_subscriptions_user_id ON public.push_subscriptions USING btree (user_id);

CREATE INDEX idx_scheduled_notifications_fire_at ON public.scheduled_notifications USING btree (fire_at);

CREATE INDEX idx_scheduled_notifications_user_id ON public.scheduled_notifications USING btree (user_id);

CREATE INDEX idx_section_exercises_section_id ON public.section_exercises USING btree (section_id);

CREATE INDEX idx_sections_coach_id ON public.sections USING btree (coach_id);

CREATE INDEX idx_stretches_body_areas ON public.stretches USING gin (body_areas);

CREATE INDEX idx_stretches_coach_id ON public.stretches USING btree (coach_id);

CREATE INDEX idx_tournaments_athlete_id ON public.tournaments USING btree (athlete_id);

CREATE INDEX idx_tournaments_date ON public.tournaments USING btree (date);

CREATE INDEX idx_tournaments_end_date ON public.tournaments USING btree (end_date);

CREATE INDEX idx_training_exercises_training_id ON public.training_exercises USING btree (training_id);

CREATE INDEX idx_training_label_links_training_id ON public.training_label_links USING btree (training_id);

CREATE INDEX idx_training_labels_coach_id ON public.training_labels USING btree (coach_id);

CREATE INDEX idx_trainings_coach_id ON public.trainings USING btree (coach_id);

CREATE INDEX idx_workout_sessions_athlete_id ON public.workout_sessions USING btree (athlete_id);

CREATE INDEX idx_workout_sessions_program_day_id ON public.workout_sessions USING btree (program_day_id);

CREATE OR REPLACE FUNCTION public.archive_exercise(p_exercise_id uuid)
 RETURNS void
 LANGUAGE sql
 SET search_path TO 'public'
AS $function$
  delete from training_exercises where exercise_id = p_exercise_id;
  delete from section_exercises where exercise_id = p_exercise_id;
  delete from program_exercises pe
  where pe.exercise_id = p_exercise_id
    and not exists (select 1 from exercise_log_sets l where l.program_exercise_id = pe.id);
  update exercises set archived = true where id = p_exercise_id;
$function$
;

CREATE OR REPLACE FUNCTION public.athlete_can_add_exercises_to_day(check_day_id uuid)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select exists (
    select 1 from program_days d join program_weeks w on w.id = d.week_id
    join programs p on p.id = w.program_id join athletes a on a.id = p.athlete_id
    where d.id = check_day_id and a.user_id = (select auth.uid()) and a.can_add_exercises = true
  );
$function$
;

CREATE OR REPLACE FUNCTION public.athlete_can_change_exercises_on_day(check_day_id uuid)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select exists (
    select 1 from program_days d join program_weeks w on w.id = d.week_id
    join programs p on p.id = w.program_id join athletes a on a.id = p.athlete_id
    where d.id = check_day_id and a.user_id = (select auth.uid()) and a.can_change_exercises = true
  );
$function$
;

CREATE OR REPLACE FUNCTION public.athlete_can_reschedule_day(check_day_id uuid)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select exists (
    select 1 from program_days d join program_weeks w on w.id = d.week_id
    join programs p on p.id = w.program_id join athletes a on a.id = p.athlete_id
    where d.id = check_day_id and a.user_id = (select auth.uid()) and a.can_reschedule_workouts = true
  );
$function$
;

CREATE OR REPLACE FUNCTION public.athlete_can_self_log(check_athlete_id bigint)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select exists (select 1 from athletes where id = check_athlete_id and user_id = (select auth.uid()) and can_self_log_workouts = true);
$function$
;

CREATE OR REPLACE FUNCTION public.athlete_notifies_own_coach(check_athlete_id bigint, target_coach_id uuid)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select exists (
    select 1 from athletes where id = check_athlete_id and user_id = (select auth.uid()) and coach_id = target_coach_id
  );
$function$
;

CREATE OR REPLACE FUNCTION public.athlete_owns_program(check_program_id uuid)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select exists (
    select 1 from programs p join athletes a on a.id = p.athlete_id
    where p.id = check_program_id and a.user_id = (select auth.uid())
  );
$function$
;

CREATE OR REPLACE FUNCTION public.athlete_owns_program_day(check_day_id uuid)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select exists (
    select 1 from program_days d join program_weeks w on w.id = d.week_id
    join programs p on p.id = w.program_id join athletes a on a.id = p.athlete_id
    where d.id = check_day_id and a.user_id = (select auth.uid())
  );
$function$
;

CREATE OR REPLACE FUNCTION public.athlete_owns_program_week(check_week_id uuid)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select exists (
    select 1 from program_weeks w join programs p on p.id = w.program_id join athletes a on a.id = p.athlete_id
    where w.id = check_week_id and a.user_id = (select auth.uid())
  );
$function$
;

CREATE OR REPLACE FUNCTION public.athlete_owns_self_logged_program(check_program_id uuid)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select exists (select 1 from programs p join athletes a on a.id = p.athlete_id
    where p.id = check_program_id and a.user_id = (select auth.uid()) and p.created_by_athlete = true);
$function$
;

CREATE OR REPLACE FUNCTION public.athlete_owns_self_logged_program_day(check_day_id uuid)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select exists (select 1 from program_days d join program_weeks w on w.id = d.week_id join programs p on p.id = w.program_id join athletes a on a.id = p.athlete_id
    where d.id = check_day_id and a.user_id = (select auth.uid()) and p.created_by_athlete = true);
$function$
;

CREATE OR REPLACE FUNCTION public.athlete_owns_self_logged_program_week(check_week_id uuid)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select exists (select 1 from program_weeks w join programs p on p.id = w.program_id join athletes a on a.id = p.athlete_id
    where w.id = check_week_id and a.user_id = (select auth.uid()) and p.created_by_athlete = true);
$function$
;

CREATE OR REPLACE FUNCTION public.athlete_schedule_range(p_athlete_id bigint, p_from date, p_to date)
 RETURNS jsonb
 LANGUAGE sql
 STABLE
 SET search_path TO 'public'
AS $function$
  with picked as (
    select d.id as day_id, w.id as week_id, p.id as program_id
    from programs p
    join program_weeks w on w.program_id = p.id
    join program_days d on d.week_id = w.id
    where p.athlete_id = p_athlete_id
      and p.is_template = false
      and (
        coalesce(d.date_override, p.start_date + ((w.week_number - 1) * 7 + (d.day_number - 1))) between p_from and p_to
        or exists (select 1 from workout_sessions s
                   where s.program_day_id = d.id and s.athlete_id = p_athlete_id and s.ended_at is null)
      )
  )
  select jsonb_build_object(
    'programs', coalesce((
      select jsonb_agg(to_jsonb(p) || jsonb_build_object('program_weeks', (
        select jsonb_agg(to_jsonb(w) || jsonb_build_object('program_days', (
          select jsonb_agg(to_jsonb(d) || jsonb_build_object('program_exercises', coalesce((
            select jsonb_agg(to_jsonb(pe) || jsonb_build_object('exercises', (
              select jsonb_build_object(
                'id', e.id, 'name', e.name, 'category', e.category, 'type', e.type,
                'video_url', e.video_url, 'foot_contacts', e.foot_contacts,
                'intensity_tier', e.intensity_tier, 'tracks_reps', e.tracks_reps,
                'tracks_weight', e.tracks_weight, 'is_timed', e.is_timed,
                'is_unilateral', e.is_unilateral, 'tracks_distance', e.tracks_distance)
              from exercises e where e.id = pe.exercise_id
            )) order by pe.order_index)
            from program_exercises pe where pe.day_id = d.id
          ), '[]'::jsonb)) order by d.day_number)
          from program_days d
          where d.week_id = w.id and d.id in (select day_id from picked)
        )) order by w.week_number)
        from program_weeks w
        where w.program_id = p.id and w.id in (select week_id from picked)
      )) order by p.start_date, p.created_at)
      from programs p
      where p.id in (select program_id from picked)
    ), '[]'::jsonb),
    'log_sets', coalesce((
      select jsonb_agg(to_jsonb(l))
      from exercise_log_sets l
      join program_exercises pe on pe.id = l.program_exercise_id
      where l.athlete_id = p_athlete_id
        and pe.day_id in (select day_id from picked)
    ), '[]'::jsonb),
    'sessions', coalesce((
      select jsonb_agg(to_jsonb(s))
      from workout_sessions s
      where s.athlete_id = p_athlete_id
        and (s.program_day_id in (select day_id from picked)
             or (s.session_type = 'mobility' and s.local_date between p_from and p_to))
    ), '[]'::jsonb)
  )
$function$
;

CREATE OR REPLACE FUNCTION public.athletes_guard_self_update()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
declare
  editable text[] := array['name', 'date_of_birth', 'gender', 'height', 'avatar_url',
                           'weight_unit', 'weekly_recap_enabled', 'intro_seen'];
begin
  if old.user_id is not null
     and old.user_id = (select auth.uid())
     and old.coach_id is distinct from (select auth.uid())
     and (to_jsonb(new) - editable) is distinct from (to_jsonb(old) - editable) then
    raise exception 'Athletes can only change their own profile settings'
      using errcode = '42501';
  end if;
  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.chat_messages_guard_athlete_update()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
begin
  if (select auth.uid()) is not null
     and old.coach_id is distinct from (select auth.uid())
     and (to_jsonb(new) - 'read_at') is distinct from (to_jsonb(old) - 'read_at') then
    raise exception 'Athletes can only mark messages as read'
      using errcode = '42501';
  end if;
  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.check_low_trainings(p_today date)
 RETURNS integer
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
declare
  v_warning_days int;
  v_added int;
begin
  select low_trainings_warning_days into v_warning_days from profiles where id = auth.uid();
  v_warning_days := coalesce(v_warning_days, 7);

  with furthest as (
    select p.athlete_id,
           max(coalesce(d.date_override, p.start_date + ((w.week_number - 1) * 7 + (d.day_number - 1)))) as furthest_date
    from programs p
    join program_weeks w on w.program_id = p.id
    join program_days d on d.week_id = w.id
    where p.is_template = false
    group by p.athlete_id
  ),
  low as (
    select a.id, a.name, f.furthest_date, coalesce(f.furthest_date::text, 'never') as notified_key
    from athletes a
    left join furthest f on f.athlete_id = a.id
    where a.coach_id = auth.uid()
      and a.user_id is not null
      and not a.archived
      and (f.furthest_date is null or f.furthest_date - p_today <= v_warning_days)
  ),
  marked as (
    update athletes a
    set low_trainings_notified_for = low.notified_key
    from low
    where a.id = low.id
      and a.low_trainings_notified_for is distinct from low.notified_key
    returning a.id, low.name, low.furthest_date
  )
  insert into notifications (coach_id, athlete_id, type, message)
  select auth.uid(), marked.id, 'low_trainings',
         case when marked.furthest_date is null
              then marked.name || ' doesn''t have any trainings scheduled yet'
              else marked.name || ' only has trainings scheduled through ' || to_char(marked.furthest_date, 'Mon FMDD')
         end
  from marked;

  get diagnostics v_added = row_count;
  return v_added;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.claim_athlete_by_email()
 RETURNS bigint
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare matched_id bigint;
begin
  select id into matched_id from athletes
  where user_id is null and email is not null and lower(email) = lower((select auth.email()));
  if matched_id is null then
    raise exception 'no unclaimed athlete found for this email';
  end if;
  update athletes set user_id = (select auth.uid()) where id = matched_id;
  return matched_id;
end; $function$
;

CREATE OR REPLACE FUNCTION public.coach_add_tournament(p_athlete_id bigint, p_name text, p_date date, p_end_date date, p_importance integer)
 RETURNS uuid
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
declare
  v_id uuid;
begin
  insert into tournaments (athlete_id, name, date, end_date, importance, created_by_coach)
  values (p_athlete_id, btrim(p_name), p_date, p_end_date, null, true)
  returning id into v_id;

  insert into tournament_coach_ratings (tournament_id, importance)
  values (v_id, p_importance);

  return v_id;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.coach_athlete_card_stats(p_today date, p_sessions_since timestamp with time zone)
 RETURNS TABLE(athlete_id bigint, furthest_date date, scheduled_30 bigint, completed_30 bigint, acwr numeric, acwr_building boolean)
 LANGUAGE sql
 STABLE
 SET search_path TO 'public'
AS $function$
  with days as (
    select d.id as day_id, p.athlete_id,
           coalesce(d.date_override, p.start_date + ((w.week_number - 1) * 7 + (d.day_number - 1))) as dt
    from programs p
    join program_weeks w on w.program_id = p.id
    join program_days d on d.week_id = w.id
    where p.is_template = false
  ),
  furthest as (
    select days.athlete_id, max(days.dt) as furthest_date
    from days
    group by days.athlete_id
  ),
  scored as (
    select days.athlete_id, days.dt,
           (sum(least(ls.done_sets, coalesce(nullif(pe.prescribed_sets, 0), 1)))::numeric
             / sum(coalesce(nullif(pe.prescribed_sets, 0), 1))) >= 0.5 as done
    from days
    join program_exercises pe on pe.day_id = days.day_id
    cross join lateral (
      select count(*) as done_sets
      from exercise_log_sets l
      where l.program_exercise_id = pe.id
        and l.completed_at is not null
        and l.set_number <= coalesce(nullif(pe.prescribed_sets, 0), 1)
        and l.date >= p_today - 29
    ) ls
    where days.dt between p_today - 29 and p_today
    group by days.athlete_id, days.day_id, days.dt
  ),
  completion as (
    select scored.athlete_id,
           count(*) filter (where scored.dt < p_today or scored.done) as scheduled_30,
           count(*) filter (where scored.done) as completed_30
    from scored
    group by scored.athlete_id
  ),
  loads as (
    select s.athlete_id, s.local_date,
           sum(s.session_rpe * extract(epoch from (s.ended_at - s.started_at)) / 60) as load
    from workout_sessions s
    where s.ended_at is not null
      and s.session_rpe is not null
      and s.started_at >= p_sessions_since
    group by s.athlete_id, s.local_date
  ),
  load_stats as (
    select loads.athlete_id,
           coalesce((p_today - min(loads.local_date) + 1) >= 28, false) as enough,
           coalesce(sum(loads.load) filter (where loads.local_date between p_today - 6 and p_today), 0) as acute,
           coalesce(sum(loads.load) filter (where loads.local_date between p_today - 27 and p_today), 0) / 4 as chronic
    from loads
    group by loads.athlete_id
  )
  select a.id as athlete_id,
         f.furthest_date,
         coalesce(c.scheduled_30, 0) as scheduled_30,
         coalesce(c.completed_30, 0) as completed_30,
         case when ls.enough and ls.chronic > 0 then ls.acute / ls.chronic end as acwr,
         coalesce(not ls.enough, false) as acwr_building
  from athletes a
  left join furthest f on f.athlete_id = a.id
  left join completion c on c.athlete_id = a.id
  left join load_stats ls on ls.athlete_id = a.id
$function$
;

CREATE OR REPLACE FUNCTION public.coach_chat_latest_messages()
 RETURNS TABLE(athlete_id bigint, message text, pdf_url text, sender text, created_at timestamp with time zone)
 LANGUAGE sql
 STABLE
 SET search_path TO 'public'
AS $function$
  select a.id as athlete_id, m.message, m.pdf_url, m.sender, m.created_at
  from athletes a
  cross join lateral (
    select cm.message, cm.pdf_url, cm.sender, cm.created_at
    from chat_messages cm
    where cm.athlete_id = a.id
    order by cm.created_at desc
    limit 1
  ) m
$function$
;

CREATE OR REPLACE FUNCTION public.coach_completion_stats(p_start date, p_end date, p_today date)
 RETURNS TABLE(athlete_id bigint, scheduled bigint, completed bigint)
 LANGUAGE sql
 STABLE
 SET search_path TO 'public'
AS $function$
  with days as (
    select d.id as day_id, p.athlete_id,
           coalesce(d.date_override, p.start_date + ((w.week_number - 1) * 7 + (d.day_number - 1))) as dt
    from programs p
    join program_weeks w on w.program_id = p.id
    join program_days d on d.week_id = w.id
    where p.is_template = false
  ),
  day_sets as (
    select pe.day_id,
           sum(coalesce(nullif(pe.prescribed_sets, 0), 1)) as total_sets,
           sum(least(
             (select count(*) from exercise_log_sets l
               where l.program_exercise_id = pe.id
                 and l.completed_at is not null
                 and l.set_number <= coalesce(nullif(pe.prescribed_sets, 0), 1)),
             coalesce(nullif(pe.prescribed_sets, 0), 1)
           )) as done_sets
    from program_exercises pe
    group by pe.day_id
  ),
  scored as (
    select days.athlete_id, days.dt,
           (s.done_sets::numeric / s.total_sets) >= 0.5 as done
    from days
    join day_sets s on s.day_id = days.day_id
  )
  select scored.athlete_id,
         count(*) as scheduled,
         count(*) filter (where scored.done) as completed
  from scored
  where scored.dt is not null
    and (p_start is null or scored.dt >= p_start)
    and scored.dt <= least(p_end, p_today)
    and (scored.dt < p_today or scored.done)
  group by scored.athlete_id
$function$
;

CREATE OR REPLACE FUNCTION public.coach_owns_program(check_program_id uuid)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select exists (select 1 from programs where id = check_program_id and coach_id = (select auth.uid()));
$function$
;

CREATE OR REPLACE FUNCTION public.coach_owns_program_day(check_day_id uuid)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select exists (
    select 1 from program_days d join program_weeks w on w.id = d.week_id join programs p on p.id = w.program_id
    where d.id = check_day_id and p.coach_id = (select auth.uid())
  );
$function$
;

CREATE OR REPLACE FUNCTION public.coach_owns_program_week(check_week_id uuid)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select exists (
    select 1 from program_weeks w join programs p on p.id = w.program_id
    where w.id = check_week_id and p.coach_id = (select auth.uid())
  );
$function$
;

CREATE OR REPLACE FUNCTION public.copy_exercise_rows(p_source_kind text, p_source_id uuid, p_section_label text DEFAULT NULL::text)
 RETURNS TABLE(rn integer, exercise_id uuid, prescribed_sets integer, prescribed_reps text, prescribed_weight numeric, rest_seconds integer, extra_fields jsonb, set_targets jsonb, notes text, section_label text, section_instance_id uuid, superset_group_id uuid, tracks_weight_override boolean, is_timed_override boolean, is_unilateral_override boolean, tracks_distance_override boolean, alternative_exercise_id uuid)
 LANGUAGE sql
 SET search_path TO 'public'
AS $function$
  with src as (
    select x.id, x.exercise_id, x.order_index, x.prescribed_sets, x.prescribed_reps, x.prescribed_weight,
           x.rest_seconds, x.extra_fields, x.set_targets, x.notes, x.section_label, x.section_instance_id,
           x.superset_group_id, x.tracks_weight_override, x.is_timed_override, x.is_unilateral_override,
           x.tracks_distance_override, x.alternative_exercise_id
    from training_exercises x where p_source_kind = 'training' and x.training_id = p_source_id
    union all
    select x.id, x.exercise_id, x.order_index, x.prescribed_sets, x.prescribed_reps, x.prescribed_weight,
           x.rest_seconds, x.extra_fields, x.set_targets, x.notes, null, null,
           x.superset_group_id, x.tracks_weight_override, x.is_timed_override, x.is_unilateral_override,
           x.tracks_distance_override, x.alternative_exercise_id
    from section_exercises x where p_source_kind = 'section' and x.section_id = p_source_id
    union all
    select x.id, x.exercise_id, x.order_index, x.prescribed_sets, x.prescribed_reps, x.prescribed_weight,
           x.rest_seconds, x.extra_fields, x.set_targets, x.notes, x.section_label, x.section_instance_id,
           x.superset_group_id, x.tracks_weight_override, x.is_timed_override, x.is_unilateral_override,
           x.tracks_distance_override, x.alternative_exercise_id
    from program_exercises x where p_source_kind = 'day' and x.day_id = p_source_id
  ),
  group_map as (
    select g.superset_group_id, gen_random_uuid() as new_id
    from (select distinct s.superset_group_id from src s where s.superset_group_id is not null) g
  ),
  section_map as (
    select g.section_instance_id, gen_random_uuid() as new_id
    from (select distinct s.section_instance_id from src s where s.section_instance_id is not null) g
  ),
  new_section as (select gen_random_uuid() as new_id)
  select
    (row_number() over (order by s.order_index, s.id) - 1)::int,
    s.exercise_id, s.prescribed_sets, s.prescribed_reps, s.prescribed_weight,
    s.rest_seconds, s.extra_fields, s.set_targets, s.notes,
    case when p_source_kind = 'section' then p_section_label else s.section_label end,
    case when p_source_kind = 'section' then ns.new_id else sm.new_id end,
    gm.new_id,
    s.tracks_weight_override, s.is_timed_override, s.is_unilateral_override,
    s.tracks_distance_override, s.alternative_exercise_id
  from src s
  cross join new_section ns
  left join group_map gm on gm.superset_group_id = s.superset_group_id
  left join section_map sm on sm.section_instance_id = s.section_instance_id
$function$
;

CREATE OR REPLACE FUNCTION public.copy_exercises(p_source_kind text, p_source_id uuid, p_target_kind text, p_target_id uuid, p_base_order integer DEFAULT NULL::integer, p_section_label text DEFAULT NULL::text)
 RETURNS TABLE(id uuid, order_index integer)
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
declare
  v_base int := p_base_order;
begin
  if p_source_kind not in ('training', 'section', 'day') or p_target_kind not in ('training', 'day') then
    raise exception 'copy_exercises: unknown kind %/%', p_source_kind, p_target_kind;
  end if;

  if p_target_kind = 'day' then
    if v_base is null then
      select coalesce(max(pe.order_index) + 1, 0) into v_base from program_exercises pe where pe.day_id = p_target_id;
    end if;
    return query
    insert into program_exercises as t (
      day_id, exercise_id, order_index, prescribed_sets, prescribed_reps, prescribed_weight,
      rest_seconds, extra_fields, set_targets, notes, section_label, section_instance_id,
      superset_group_id, tracks_weight_override, is_timed_override, is_unilateral_override,
      tracks_distance_override, alternative_exercise_id
    )
    select p_target_id, r.exercise_id, v_base + r.rn, r.prescribed_sets, r.prescribed_reps, r.prescribed_weight,
           r.rest_seconds, r.extra_fields, r.set_targets, r.notes, r.section_label, r.section_instance_id,
           r.superset_group_id, r.tracks_weight_override, r.is_timed_override, r.is_unilateral_override,
           r.tracks_distance_override, r.alternative_exercise_id
    from copy_exercise_rows(p_source_kind, p_source_id, p_section_label) r
    returning t.id, t.order_index;
  else
    if v_base is null then
      select coalesce(max(te.order_index) + 1, 0) into v_base from training_exercises te where te.training_id = p_target_id;
    end if;
    return query
    insert into training_exercises as t (
      training_id, exercise_id, order_index, prescribed_sets, prescribed_reps, prescribed_weight,
      rest_seconds, extra_fields, set_targets, notes, section_label, section_instance_id,
      superset_group_id, tracks_weight_override, is_timed_override, is_unilateral_override,
      tracks_distance_override, alternative_exercise_id
    )
    select p_target_id, r.exercise_id, v_base + r.rn, r.prescribed_sets, r.prescribed_reps, r.prescribed_weight,
           r.rest_seconds, r.extra_fields, r.set_targets, r.notes, r.section_label, r.section_instance_id,
           r.superset_group_id, r.tracks_weight_override, r.is_timed_override, r.is_unilateral_override,
           r.tracks_distance_override, r.alternative_exercise_id
    from copy_exercise_rows(p_source_kind, p_source_id, p_section_label) r
    returning t.id, t.order_index;
  end if;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.copy_program(p_source_program_id uuid, p_name text DEFAULT NULL::text, p_athlete_id bigint DEFAULT NULL::bigint, p_start_date date DEFAULT NULL::date, p_range_start integer DEFAULT NULL::integer, p_range_end integer DEFAULT NULL::integer)
 RETURNS uuid
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
declare
  v_new uuid;
begin
  if not exists (select 1 from programs p where p.id = p_source_program_id) then
    raise exception 'copy_program: program not found';
  end if;

  insert into programs (coach_id, athlete_id, is_template, is_adhoc, name, start_date)
  values ((select auth.uid()), p_athlete_id, p_athlete_id is null, false,
          coalesce(p_name, (select p.name from programs p where p.id = p_source_program_id)), p_start_date)
  returning id into v_new;

  insert into program_weeks (program_id, week_number)
  select v_new, w.week_number from program_weeks w
  where w.program_id = p_source_program_id
    and ((p_range_start is null and p_range_end is null)
         or exists (select 1 from copy_program_days_in_range(p_source_program_id, p_range_start, p_range_end) c
                    where c.week_number = w.week_number));

  insert into program_days (week_id, day_number, label, workout_type, source_training_id, source_training_synced_at)
  select nw.id, d.day_number, d.label, d.workout_type, d.source_training_id, null
  from copy_program_days_in_range(p_source_program_id, p_range_start, p_range_end) c
  join program_days d on d.id = c.src_day
  join program_weeks nw on nw.program_id = v_new and nw.week_number = c.week_number;

  -- One superset / section-instance map for the whole program: the
  -- originals are already unique, so there's nothing to collide with.
  with src as (
    select pe.*, c.week_number, c.day_number
    from program_exercises pe
    join copy_program_days_in_range(p_source_program_id, p_range_start, p_range_end) c on c.src_day = pe.day_id
  ),
  group_map as (
    select g.superset_group_id, gen_random_uuid() as new_id
    from (select distinct s.superset_group_id from src s where s.superset_group_id is not null) g
  ),
  section_map as (
    select g.section_instance_id, gen_random_uuid() as new_id
    from (select distinct s.section_instance_id from src s where s.section_instance_id is not null) g
  )
  insert into program_exercises (
    day_id, exercise_id, order_index, prescribed_sets, prescribed_reps, prescribed_weight,
    rest_seconds, extra_fields, set_targets, notes, section_label, section_instance_id,
    superset_group_id, tracks_weight_override, is_timed_override, is_unilateral_override,
    tracks_distance_override, alternative_exercise_id
  )
  select nd.id, s.exercise_id, s.order_index, s.prescribed_sets, s.prescribed_reps, s.prescribed_weight,
         s.rest_seconds, s.extra_fields, s.set_targets, s.notes, s.section_label, sm.new_id,
         gm.new_id, s.tracks_weight_override, s.is_timed_override, s.is_unilateral_override,
         s.tracks_distance_override, s.alternative_exercise_id
  from src s
  join program_weeks nw on nw.program_id = v_new and nw.week_number = s.week_number
  join program_days nd on nd.week_id = nw.id and nd.day_number = s.day_number
  left join group_map gm on gm.superset_group_id = s.superset_group_id
  left join section_map sm on sm.section_instance_id = s.section_instance_id;

  return v_new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.copy_program_days_in_range(p_program_id uuid, p_range_start integer, p_range_end integer)
 RETURNS TABLE(src_day uuid, week_number integer, day_number integer)
 LANGUAGE sql
 SET search_path TO 'public'
AS $function$
  select d.id, w.week_number, d.day_number
  from program_days d join program_weeks w on w.id = d.week_id
  where w.program_id = p_program_id
    and (p_range_start is null or (w.week_number - 1) * 7 + d.day_number >= p_range_start)
    and (p_range_end is null or (w.week_number - 1) * 7 + d.day_number <= p_range_end)
$function$
;

CREATE OR REPLACE FUNCTION public.create_adhoc_day(p_coach_id uuid, p_athlete_id bigint, p_date date, p_name text, p_workout_type text DEFAULT NULL::text, p_created_by_athlete boolean DEFAULT false)
 RETURNS uuid
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
declare
  v_program_id uuid;
  v_week_id uuid;
  v_day_id uuid;
begin
  insert into programs (coach_id, athlete_id, is_template, is_adhoc, created_by_athlete, start_date, name)
  values (p_coach_id, p_athlete_id, false, true, p_created_by_athlete, p_date, p_name)
  returning id into v_program_id;

  insert into program_weeks (program_id, week_number)
  values (v_program_id, 1)
  returning id into v_week_id;

  insert into program_days (week_id, day_number, workout_type)
  values (v_week_id, 1, p_workout_type)
  returning id into v_day_id;

  return v_day_id;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.delete_stretch_area(p_area text)
 RETURNS void
 LANGUAGE sql
 SET search_path TO 'public'
AS $function$
  update stretches set body_areas = array_remove(body_areas, p_area) where p_area = any(body_areas);
  delete from stretch_body_areas where name = p_area;
$function$
;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  insert into public.profiles (id, role, name)
  values (new.id, coalesce(new.raw_user_meta_data ->> 'role', 'athlete'),
          coalesce(new.raw_user_meta_data ->> 'name', ''))
  on conflict (id) do nothing;
  return new;
end; $function$
;

CREATE OR REPLACE FUNCTION public.is_coach()
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select exists (select 1 from public.profiles where id = (select auth.uid()) and role = 'coach');
$function$
;

CREATE OR REPLACE FUNCTION public.is_my_coach(check_coach_id uuid)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select exists (select 1 from athletes where user_id = (select auth.uid()) and coach_id = check_coach_id);
$function$
;

CREATE OR REPLACE FUNCTION public.is_own_athlete_as_athlete(check_athlete_id bigint)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select exists (select 1 from athletes where id = check_athlete_id and user_id = (select auth.uid()));
$function$
;

CREATE OR REPLACE FUNCTION public.is_own_athlete_as_coach(check_athlete_id bigint)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select exists (select 1 from athletes where id = check_athlete_id and coach_id = (select auth.uid()));
$function$
;

CREATE OR REPLACE FUNCTION public.program_day_matches_athlete(check_day_id uuid, check_athlete_id bigint)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select exists (
    select 1 from program_days d
    join program_weeks w on w.id = d.week_id
    join programs p on p.id = w.program_id
    where d.id = check_day_id and p.athlete_id = check_athlete_id
  );
$function$
;

CREATE OR REPLACE FUNCTION public.program_exercise_matches_athlete(check_pe_id uuid, check_athlete_id bigint)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select exists (
    select 1 from program_exercises pe
    join program_days d on d.id = pe.day_id
    join program_weeks w on w.id = d.week_id
    join programs p on p.id = w.program_id
    where pe.id = check_pe_id and p.athlete_id = check_athlete_id
  );
$function$
;

CREATE OR REPLACE FUNCTION public.rename_stretch_area(p_old text, p_new text)
 RETURNS void
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
begin
  update stretches s
  set body_areas = (
    select array_agg(x.area order by x.first_pos)
    from (
      select t.area, min(t.pos) as first_pos
      from unnest(array_replace(s.body_areas, p_old, p_new)) with ordinality as t(area, pos)
      group by t.area
    ) x
  )
  where p_old = any(s.body_areas);

  if exists (select 1 from stretch_body_areas where name = p_new) then
    delete from stretch_body_areas where name = p_old;
  else
    update stretch_body_areas set name = p_new where name = p_old;
  end if;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.sync_live_training_days(p_day_ids uuid[])
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_day record;
begin
  for v_day in
    select pd.id as day_id, pd.source_training_id, pd.source_training_synced_at, p.is_template
    from program_days pd
    join program_weeks pw on pw.id = pd.week_id
    join programs p on p.id = pw.program_id
    where pd.id = any(p_day_ids)
      and pd.source_training_id is not null
      and (
        p.coach_id = (select auth.uid())
        or exists (select 1 from athletes a where a.id = p.athlete_id and a.user_id = (select auth.uid()))
      )
  loop
    -- An athlete-owned day that's already been started detaches instead of
    -- syncing - the exercise list can't change out from under a workout in
    -- progress. (The app also clears this eagerly at Start Workout time -
    -- this is a defense-in-depth backstop, not the primary path.)
    if not v_day.is_template and exists (
      select 1 from workout_sessions ws where ws.program_day_id = v_day.day_id
    ) then
      update program_days set source_training_id = null, source_training_synced_at = null where id = v_day.day_id;
      continue;
    end if;

    -- Already matches the Training's current version - skip the rewrite
    if v_day.source_training_synced_at is not null and v_day.source_training_synced_at >= (
      select t.updated_at from trainings t where t.id = v_day.source_training_id
    ) then
      continue;
    end if;

    delete from program_exercises where day_id = v_day.day_id;
    perform copy_exercises('training', v_day.source_training_id, 'day', v_day.day_id, 0);

    update program_days
    set source_training_synced_at = (select t.updated_at from trainings t where t.id = v_day.source_training_id)
    where id = v_day.day_id;
  end loop;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.touch_training_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
begin
  update trainings set updated_at = now() where id = coalesce(new.training_id, old.training_id);
  return coalesce(new, old);
end; $function$
;

CREATE OR REPLACE FUNCTION public.touch_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
begin
  new.updated_at = now();
  return new;
end; $function$
;

CREATE TRIGGER athletes_guard_self_update BEFORE UPDATE ON public.athletes FOR EACH ROW EXECUTE FUNCTION athletes_guard_self_update();

CREATE TRIGGER chat_messages_guard_athlete_update BEFORE UPDATE ON public.chat_messages FOR EACH ROW EXECUTE FUNCTION chat_messages_guard_athlete_update();

CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION handle_new_user();

CREATE TRIGGER training_exercises_touch_parent AFTER INSERT OR DELETE OR UPDATE ON public.training_exercises FOR EACH ROW EXECUTE FUNCTION touch_training_updated_at();

CREATE TRIGGER trainings_touch_updated_at BEFORE UPDATE ON public.trainings FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

alter table athlete_label_links enable row level security;

alter table athlete_labels enable row level security;

alter table athlete_metrics enable row level security;

alter table athlete_notes enable row level security;

alter table athlete_stretch_preferences enable row level security;

alter table athletes enable row level security;

alter table bodyweight enable row level security;

alter table chat_messages enable row level security;

alter table coach_messages enable row level security;

alter table exercise_log_sets enable row level security;

alter table exercises enable row level security;

alter table extra_field_names enable row level security;

alter table form_answers enable row level security;

alter table form_assignments enable row level security;

alter table form_questions enable row level security;

alter table forms enable row level security;

alter table measurements enable row level security;

alter table metrics enable row level security;

alter table notifications enable row level security;

alter table profiles enable row level security;

alter table program_days enable row level security;

alter table program_exercises enable row level security;

alter table program_weeks enable row level security;

alter table programs enable row level security;

alter table push_subscriptions enable row level security;

alter table scheduled_notifications enable row level security;

alter table section_exercises enable row level security;

alter table sections enable row level security;

alter table stretch_body_areas enable row level security;

alter table stretches enable row level security;

alter table tournament_coach_ratings enable row level security;

alter table tournaments enable row level security;

alter table training_exercises enable row level security;

alter table training_label_links enable row level security;

alter table training_labels enable row level security;

alter table trainings enable row level security;

alter table workout_sessions enable row level security;

create policy "coach manages own athlete label links" on athlete_label_links as permissive for all to public
  using (is_own_athlete_as_coach(athlete_id))
  with check (is_own_athlete_as_coach(athlete_id));

create policy "coach manages own athlete labels" on athlete_labels as permissive for all to public
  using ((coach_id = auth.uid()))
  with check ((coach_id = auth.uid()));

create policy "coach manages own athletes athlete_metrics" on athlete_metrics as permissive for all to public
  using (is_own_athlete_as_coach(athlete_id))
  with check (is_own_athlete_as_coach(athlete_id));

create policy "coach manages own athletes notes" on athlete_notes as permissive for all to public
  using (is_own_athlete_as_coach(athlete_id))
  with check (is_own_athlete_as_coach(athlete_id));

create policy "athlete manages own stretch preferences" on athlete_stretch_preferences as permissive for all to public
  using (is_own_athlete_as_athlete(athlete_id))
  with check (is_own_athlete_as_athlete(athlete_id));

create policy "athlete can view own row" on athletes as permissive for select to public
  using ((user_id = ( SELECT auth.uid() AS uid)));

create policy "athlete updates own settings" on athletes as permissive for update to public
  using ((user_id = ( SELECT auth.uid() AS uid)))
  with check ((user_id = ( SELECT auth.uid() AS uid)));

create policy "coach full access to own athletes" on athletes as permissive for all to public
  using ((coach_id = ( SELECT auth.uid() AS uid)))
  with check ((coach_id = ( SELECT auth.uid() AS uid)));

create policy "athlete manages own bodyweight" on bodyweight as permissive for all to public
  using (is_own_athlete_as_athlete(athlete_id))
  with check (is_own_athlete_as_athlete(athlete_id));

create policy "coach manages own athletes bodyweight" on bodyweight as permissive for all to public
  using (is_own_athlete_as_coach(athlete_id))
  with check (is_own_athlete_as_coach(athlete_id));

create policy "athlete marks coach messages read" on chat_messages as permissive for update to public
  using (((sender = 'coach'::text) AND is_own_athlete_as_athlete(athlete_id)))
  with check (((sender = 'coach'::text) AND is_own_athlete_as_athlete(athlete_id)));

create policy "athlete reads own chat" on chat_messages as permissive for select to public
  using (is_own_athlete_as_athlete(athlete_id));

create policy "athlete sends to own coach" on chat_messages as permissive for insert to public
  with check (((sender = 'athlete'::text) AND (pdf_url IS NULL) AND athlete_notifies_own_coach(athlete_id, coach_id)));

create policy "coach manages own chats" on chat_messages as permissive for all to public
  using ((coach_id = ( SELECT auth.uid() AS uid)))
  with check (((coach_id = ( SELECT auth.uid() AS uid)) AND is_own_athlete_as_coach(athlete_id)));

create policy "athlete marks own messages seen" on coach_messages as permissive for update to public
  using (is_own_athlete_as_athlete(athlete_id))
  with check (is_own_athlete_as_athlete(athlete_id));

create policy "athlete views own messages" on coach_messages as permissive for select to public
  using (is_own_athlete_as_athlete(athlete_id));

create policy "coach manages own messages" on coach_messages as permissive for all to public
  using ((coach_id = ( SELECT auth.uid() AS uid)))
  with check ((coach_id = ( SELECT auth.uid() AS uid)));

create policy "athlete manages own log sets" on exercise_log_sets as permissive for all to public
  using (is_own_athlete_as_athlete(athlete_id))
  with check ((is_own_athlete_as_athlete(athlete_id) AND program_exercise_matches_athlete(program_exercise_id, athlete_id)));

create policy "coach views log sets for own athletes" on exercise_log_sets as permissive for select to public
  using (is_own_athlete_as_coach(athlete_id));

create policy "athlete views own coach's exercises" on exercises as permissive for select to public
  using (is_my_coach(coach_id));

create policy "coach manages own exercise library" on exercises as permissive for all to public
  using ((coach_id = ( SELECT auth.uid() AS uid)))
  with check (((coach_id = ( SELECT auth.uid() AS uid)) AND is_coach()));

create policy "coach manages own extra field names" on extra_field_names as permissive for all to public
  using ((coach_id = ( SELECT auth.uid() AS uid)))
  with check ((coach_id = ( SELECT auth.uid() AS uid)));

create policy "athlete manages own form answers" on form_answers as permissive for all to public
  using ((EXISTS ( SELECT 1
   FROM (form_assignments fa
     JOIN athletes a ON ((a.id = fa.athlete_id)))
  WHERE ((fa.id = form_answers.assignment_id) AND (a.user_id = ( SELECT auth.uid() AS uid))))))
  with check ((EXISTS ( SELECT 1
   FROM (form_assignments fa
     JOIN athletes a ON ((a.id = fa.athlete_id)))
  WHERE ((fa.id = form_answers.assignment_id) AND (a.user_id = ( SELECT auth.uid() AS uid))))));

create policy "coach views own athletes form answers" on form_answers as permissive for select to public
  using ((EXISTS ( SELECT 1
   FROM form_assignments fa
  WHERE ((fa.id = form_answers.assignment_id) AND (fa.coach_id = ( SELECT auth.uid() AS uid))))));

create policy "athlete completes own form assignments" on form_assignments as permissive for update to public
  using (is_own_athlete_as_athlete(athlete_id))
  with check (is_own_athlete_as_athlete(athlete_id));

create policy "athlete views own form assignments" on form_assignments as permissive for select to public
  using (is_own_athlete_as_athlete(athlete_id));

create policy "coach manages own form assignments" on form_assignments as permissive for all to public
  using ((coach_id = ( SELECT auth.uid() AS uid)))
  with check ((coach_id = ( SELECT auth.uid() AS uid)));

create policy "athlete views own assigned form questions" on form_questions as permissive for select to public
  using ((EXISTS ( SELECT 1
   FROM (form_assignments fa
     JOIN athletes a ON ((a.id = fa.athlete_id)))
  WHERE ((fa.form_id = form_questions.form_id) AND (a.user_id = ( SELECT auth.uid() AS uid))))));

create policy "coach manages own form questions" on form_questions as permissive for all to public
  using ((EXISTS ( SELECT 1
   FROM forms f
  WHERE ((f.id = form_questions.form_id) AND (f.coach_id = ( SELECT auth.uid() AS uid))))))
  with check ((EXISTS ( SELECT 1
   FROM forms f
  WHERE ((f.id = form_questions.form_id) AND (f.coach_id = ( SELECT auth.uid() AS uid))))));

create policy "coach manages own forms" on forms as permissive for all to public
  using ((coach_id = ( SELECT auth.uid() AS uid)))
  with check ((coach_id = ( SELECT auth.uid() AS uid)));

create policy "coach manages own athletes measurements" on measurements as permissive for all to public
  using (is_own_athlete_as_coach(athlete_id))
  with check (is_own_athlete_as_coach(athlete_id));

create policy "coaches manage global metrics library" on metrics as permissive for all to public
  using (is_coach())
  with check (is_coach());

create policy "athlete creates notifications for own coach" on notifications as permissive for insert to public
  with check (athlete_notifies_own_coach(athlete_id, coach_id));

create policy "coach creates own notifications" on notifications as permissive for insert to public
  with check ((coach_id = ( SELECT auth.uid() AS uid)));

create policy "coach manages own notifications" on notifications as permissive for all to public
  using ((coach_id = ( SELECT auth.uid() AS uid)))
  with check ((coach_id = ( SELECT auth.uid() AS uid)));

create policy "athlete views own coach's profile" on profiles as permissive for select to public
  using (is_my_coach(id));

create policy "select own profile" on profiles as permissive for select to public
  using ((id = ( SELECT auth.uid() AS uid)));

create policy "update own profile" on profiles as permissive for update to public
  using ((id = ( SELECT auth.uid() AS uid)))
  with check ((id = ( SELECT auth.uid() AS uid)));

create policy "athlete manages own self-logged program days" on program_days as permissive for all to public
  using (athlete_owns_self_logged_program_day(id))
  with check (athlete_owns_self_logged_program_week(week_id));

create policy "athlete reschedules days when allowed" on program_days as permissive for update to public
  using (athlete_can_reschedule_day(id))
  with check (athlete_can_reschedule_day(id));

create policy "athlete views own program days" on program_days as permissive for select to public
  using (athlete_owns_program_week(week_id));

create policy "coach manages own program days" on program_days as permissive for all to public
  using (coach_owns_program_week(week_id))
  with check (coach_owns_program_week(week_id));

create policy "athlete adds extra exercises when allowed" on program_exercises as permissive for insert to public
  with check (athlete_can_add_exercises_to_day(day_id));

create policy "athlete deletes own added exercises" on program_exercises as permissive for delete to public
  using (((added_by_athlete = true) AND athlete_owns_program_day(day_id)));

create policy "athlete manages own self-logged program exercises" on program_exercises as permissive for all to public
  using (athlete_owns_self_logged_program_day(day_id))
  with check (athlete_owns_self_logged_program_day(day_id));

create policy "athlete swaps exercises when allowed" on program_exercises as permissive for update to public
  using (athlete_can_change_exercises_on_day(day_id))
  with check (athlete_can_change_exercises_on_day(day_id));

create policy "athlete views own program exercises" on program_exercises as permissive for select to public
  using (athlete_owns_program_day(day_id));

create policy "coach manages own program exercises" on program_exercises as permissive for all to public
  using (coach_owns_program_day(day_id))
  with check (coach_owns_program_day(day_id));

create policy "athlete manages own self-logged program weeks" on program_weeks as permissive for all to public
  using (athlete_owns_self_logged_program_week(id))
  with check (athlete_owns_self_logged_program(program_id));

create policy "athlete views own program weeks" on program_weeks as permissive for select to public
  using (athlete_owns_program(program_id));

create policy "coach manages own program weeks" on program_weeks as permissive for all to public
  using (coach_owns_program(program_id))
  with check (coach_owns_program(program_id));

create policy "athlete creates own self-logged programs" on programs as permissive for insert to public
  with check ((athlete_notifies_own_coach(athlete_id, coach_id) AND athlete_can_self_log(athlete_id) AND (is_adhoc = true) AND (NOT is_template) AND (created_by_athlete = true)));

create policy "athlete deletes own self-logged programs" on programs as permissive for delete to public
  using ((is_own_athlete_as_athlete(athlete_id) AND (created_by_athlete = true)));

create policy "athlete views own programs" on programs as permissive for select to public
  using (is_own_athlete_as_athlete(athlete_id));

create policy "coach manages own programs" on programs as permissive for all to public
  using (((coach_id = ( SELECT auth.uid() AS uid)) AND ((athlete_id IS NULL) OR is_own_athlete_as_coach(athlete_id))))
  with check (((coach_id = ( SELECT auth.uid() AS uid)) AND is_coach() AND ((is_template AND (athlete_id IS NULL)) OR ((NOT is_template) AND (athlete_id IS NOT NULL) AND is_own_athlete_as_coach(athlete_id)))));

create policy "user manages own push subscriptions" on push_subscriptions as permissive for all to public
  using ((user_id = ( SELECT auth.uid() AS uid)))
  with check ((user_id = ( SELECT auth.uid() AS uid)));

create policy "user manages own scheduled notifications" on scheduled_notifications as permissive for all to public
  using ((user_id = ( SELECT auth.uid() AS uid)))
  with check ((user_id = ( SELECT auth.uid() AS uid)));

create policy "coach manages own section exercises" on section_exercises as permissive for all to public
  using ((EXISTS ( SELECT 1
   FROM sections s
  WHERE ((s.id = section_exercises.section_id) AND (s.coach_id = ( SELECT auth.uid() AS uid))))))
  with check ((EXISTS ( SELECT 1
   FROM sections s
  WHERE ((s.id = section_exercises.section_id) AND (s.coach_id = ( SELECT auth.uid() AS uid))))));

create policy "coach manages own sections" on sections as permissive for all to public
  using ((coach_id = ( SELECT auth.uid() AS uid)))
  with check ((coach_id = ( SELECT auth.uid() AS uid)));

create policy "athlete manages own avatar" on storage.objects as permissive for all to public
  using (((bucket_id = 'athlete-avatars'::text) AND ((( SELECT auth.uid() AS uid))::text = (storage.foldername(name))[1])))
  with check (((bucket_id = 'athlete-avatars'::text) AND ((( SELECT auth.uid() AS uid))::text = (storage.foldername(name))[1])));

create policy "athlete reads reports sent to them" on storage.objects as permissive for select to authenticated
  using (((bucket_id = 'chat-attachments'::text) AND (EXISTS ( SELECT 1
   FROM (chat_messages m
     JOIN athletes a ON ((a.id = m.athlete_id)))
  WHERE ((a.user_id = ( SELECT auth.uid() AS uid)) AND (m.pdf_url ~~ ('%/chat-attachments/'::text || objects.name)))))));

create policy "coach manages own chat attachments" on storage.objects as permissive for all to public
  using (((bucket_id = 'chat-attachments'::text) AND ((( SELECT auth.uid() AS uid))::text = (storage.foldername(name))[1])))
  with check (((bucket_id = 'chat-attachments'::text) AND ((( SELECT auth.uid() AS uid))::text = (storage.foldername(name))[1]) AND is_coach()));

create policy "coach manages own stretch videos" on storage.objects as permissive for all to public
  using (((bucket_id = 'stretch-videos'::text) AND ((( SELECT auth.uid() AS uid))::text = (storage.foldername(name))[1])))
  with check (((bucket_id = 'stretch-videos'::text) AND ((( SELECT auth.uid() AS uid))::text = (storage.foldername(name))[1]) AND is_coach()));

create policy "public reads athlete avatars" on storage.objects as permissive for select to public
  using ((bucket_id = 'athlete-avatars'::text));

create policy "public reads stretch videos" on storage.objects as permissive for select to public
  using ((bucket_id = 'stretch-videos'::text));

create policy "coach manages own stretch areas" on stretch_body_areas as permissive for all to public
  using ((coach_id = ( SELECT auth.uid() AS uid)))
  with check (((coach_id = ( SELECT auth.uid() AS uid)) AND is_coach()));

create policy "athlete views own coach's stretches" on stretches as permissive for select to public
  using (is_my_coach(coach_id));

create policy "coach manages own stretch library" on stretches as permissive for all to public
  using ((coach_id = ( SELECT auth.uid() AS uid)))
  with check (((coach_id = ( SELECT auth.uid() AS uid)) AND is_coach()));

create policy "coach manages own athletes' tournament ratings" on tournament_coach_ratings as permissive for all to public
  using ((EXISTS ( SELECT 1
   FROM tournaments t
  WHERE ((t.id = tournament_coach_ratings.tournament_id) AND is_own_athlete_as_coach(t.athlete_id)))))
  with check ((EXISTS ( SELECT 1
   FROM tournaments t
  WHERE ((t.id = tournament_coach_ratings.tournament_id) AND is_own_athlete_as_coach(t.athlete_id)))));

create policy "athlete adds own tournaments" on tournaments as permissive for insert to public
  with check ((is_own_athlete_as_athlete(athlete_id) AND (NOT created_by_coach)));

create policy "athlete deletes own tournaments" on tournaments as permissive for delete to public
  using ((is_own_athlete_as_athlete(athlete_id) AND (NOT created_by_coach)));

create policy "athlete edits own tournaments" on tournaments as permissive for update to public
  using ((is_own_athlete_as_athlete(athlete_id) AND (NOT created_by_coach)))
  with check ((is_own_athlete_as_athlete(athlete_id) AND (NOT created_by_coach)));

create policy "athlete views own tournaments" on tournaments as permissive for select to public
  using (is_own_athlete_as_athlete(athlete_id));

create policy "coach adds tournaments for own athletes" on tournaments as permissive for insert to public
  with check ((is_own_athlete_as_coach(athlete_id) AND created_by_coach));

create policy "coach deletes tournaments they added" on tournaments as permissive for delete to public
  using ((is_own_athlete_as_coach(athlete_id) AND created_by_coach));

create policy "coach views own athletes' tournaments" on tournaments as permissive for select to public
  using (is_own_athlete_as_coach(athlete_id));

create policy "coach manages own training exercises" on training_exercises as permissive for all to public
  using ((EXISTS ( SELECT 1
   FROM trainings t
  WHERE ((t.id = training_exercises.training_id) AND (t.coach_id = ( SELECT auth.uid() AS uid))))))
  with check ((EXISTS ( SELECT 1
   FROM trainings t
  WHERE ((t.id = training_exercises.training_id) AND (t.coach_id = ( SELECT auth.uid() AS uid))))));

create policy "coach manages own training label links" on training_label_links as permissive for all to public
  using ((EXISTS ( SELECT 1
   FROM trainings t
  WHERE ((t.id = training_label_links.training_id) AND (t.coach_id = ( SELECT auth.uid() AS uid))))))
  with check ((EXISTS ( SELECT 1
   FROM trainings t
  WHERE ((t.id = training_label_links.training_id) AND (t.coach_id = ( SELECT auth.uid() AS uid))))));

create policy "coach manages own training labels" on training_labels as permissive for all to public
  using ((coach_id = ( SELECT auth.uid() AS uid)))
  with check ((coach_id = ( SELECT auth.uid() AS uid)));

create policy "coach manages own trainings" on trainings as permissive for all to public
  using ((coach_id = ( SELECT auth.uid() AS uid)))
  with check ((coach_id = ( SELECT auth.uid() AS uid)));

create policy "athlete manages own sessions" on workout_sessions as permissive for all to public
  using (is_own_athlete_as_athlete(athlete_id))
  with check ((is_own_athlete_as_athlete(athlete_id) AND (((session_type = 'training'::text) AND program_day_matches_athlete(program_day_id, athlete_id)) OR ((session_type = 'mobility'::text) AND (program_day_id IS NULL)))));

create policy "coach deletes sessions for own athletes" on workout_sessions as permissive for delete to public
  using (is_own_athlete_as_coach(athlete_id));

create policy "coach reviews sessions for own athletes" on workout_sessions as permissive for update to public
  using (is_own_athlete_as_coach(athlete_id))
  with check (is_own_athlete_as_coach(athlete_id));

create policy "coach views sessions for own athletes" on workout_sessions as permissive for select to public
  using (is_own_athlete_as_coach(athlete_id));
